services:
  - type: web
    name: mumu-mini-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: OWNER_NUMBER
        value: "263776719736"
      - key: PREFIX
        value: "/"
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
